### ISSUE TITLE
Duplicate node appear when using xml file to generate .c .h file

### ISSUE THREAD

**Issue by xty19** [open62541/open62541#1004]
Description
===========
i use UaModeler to generate xml file and use open62541 to generate .c and .h file to add variables
ps: i use UaModeler define my own BaseObjectType  "DeviceObjectType" in  BaseObjectType of ObjectTypes, and i create an instance  "Folder" in Objects folder . But when i add it to server and use UaExpert to browse the varibales , it shows duplicate variables! 
![qq 20170406111645](https://cloud.githubusercontent.com/assets/9359167/24736332/fa63f166-1ab9-11e7-9b68-3c3295cd3603.png)
![qq 20170406110808](https://cloud.githubusercontent.com/assets/9359167/24736333/fab37178-1ab9-11e7-8dd1-00a3afaea8c5.png)

 - [x] open62541 Version (release number or git tag): v0.2.0-RC1
 - [x] Other OPC UA SDKs used (client or server): server
 - [x] Operating system:81~precise1-Ubuntu SMP

**Comment by jpfr** [comment]
This looks like an artefact of the node instantiation.
Probably you have the child variables defined for the objecttypes.
The stack automatically instantiates the children together with the object.

And then, the children get added a second time via the nodeset xml model.

@open62541/open62541-core @ichrispa 
Are you okay with adding an additional check for Mandatory and Optional variables for 0.2?
This is defined via an additional references in the objecttype.
If nothing is defined, we then assume "Optional" and don't automatically instantiate children.
Otherwise, this problem will persist throughout the 0.2 release series.

**Comment by Pro** [comment]
I ran into the same problem some months ago, where I imported the devices profile via xml into open62541. There I did some hardcoding to fix it, but your proposed is definitely better.

**Comment by xty19** [comment]
@jpfr 
its ok to add variables. for 0.2
it goes wrong just adding diy objecttype.


[

](url)

**Comment by jpfr** [comment]
Fixed with ee5361074746b2eb125921edb049f6d24cb70ce0.
We now auto-instantiate only those children that are marked as mandatory.
