### ISSUE TITLE
Segmentation fault after running 3 days with above 1000 real time updating nodes [Again]

### ISSUE THREAD

**Issue by JinGuoGe** [open62541/open62541#1068]
Hi, This is duplicated issue #1050
My testing device's RAM is 128Mbyte
I will write here my test opcserver code. it still crashes after 2 days running.
why does it need multihreading-safe? Could you explain in detail?
https://paste2.org/nEVbAXmV

I also checked valgrind, there is no memory leak.
-Following url is crashed log of gdb.(mentioned in former issue)
https://paste2.org/KneaeV68

**Comment by jpfr** [comment]
> why does it need multihreading-safe? Could you explain in detail?

Shared memory. The two threads access the same memory of the server.
But during an operation, the server can be in an inconsistent state.
This can lead to errors when a second thread accesses the server at the same time. And sees inconsistent memory. That is called a race condition (https://en.wikipedia.org/wiki/Race_condition).

Two options:
- Protect the server structure with a mutex. So that only one thread can work on the server at the same time.
- Use only one thread for the application logic and the server. You can call the `UA_Server_run_iterate` method to drive the server from an external main loop

This is WONTFIX. Please reopen when there are problems in applying any of the solutions I mentioned.
Or when further issues come up that are not related to unprotected access to shared memory.
