### ISSUE TITLE
Prosys client crashes with open62541 server (on master) 

### ISSUE THREAD

**Issue by XB32Z** [open62541/open62541#1107]
Hi all, 

I am using the Java Prosys stack client to connect to my open62541 server. This worked for version 0.2 however on the master the client cannot find the endpoints and crashes with a EOF exception. 

I tried on different platforms, without certificates but it didn't solved the issue. Was there something changed on the lowest level since v0.2? I lowered the log to trace and I don't even get a notification that the client tried to connect. (But it works with 0.2) 

For more information, [here is the link to the issue on their forum](https://forum.prosysopc.com/forum/opc-ua-java-sdk/cant-connect-to-open62541/)

Best,

**Comment by jpfr** [comment]
Hey Pierre,

We are testing against the official Conformance Testing Tools of the OPC Foundation as well.
The tests are green. This is a screenshot of the tests for the "GetEndpoints" service on the current master branch.

![getendpoints](https://user-images.githubusercontent.com/1726411/28104308-ab2f59ce-66da-11e7-856b-d0a4795f422c.png)

A possible cause for this bug is the recent switch to dual IPv4 / IPv6. We now use IPv6 if available.

By the way, I don't understand the attitude of not fixing a crashing bug from a normal network packet.
Whether this is our "fault" or not.
The Prosys SDK should expect and protect against malicious input as industrial applications are getting targeted by hackers. Crashing bugs are at least a denial of service and could even be exploitable to take over the computer.

I have only a few minutes time today. Will investigate with the Prosys SDK itself at the end of the week.

**Comment by XB32Z** [comment]
Hi, 

Thank you for your answer, I will investigate the IPv6 lead. I agree with you regarding the Prosys position. I hope they'll investigate it too. 

Best,
Pierre

**Comment by XB32Z** [comment]
Hi, 
Did you have any success with this?
Thx

**Comment by jouniaro** [comment]
I just updated the issue in Prosys OPC Forum, but I decided to copy it here as well, if you find it easier:

Might be an issue with Java, but with the current knowledge there is nothing else we can do. The socket is giving an EOFException, which is being raised properly as a ServiceResultException: Bad_CommunicationError. I cannot figure out any better error handling for this situation.

IMO, it is a bit exaggerated to label this as ‘crash’. The client application just fails to connect. OTOH, I am not sure what happens in the server.

Anyway, we are glad to help in sorting this issue out, if you find out more information about the problem. With the current knowledge we don’t know how to target this.

The Java stack should also support IPV6 in general, although it has not been used very extensively. I would find it better to support IPV4 as long as it is available, anyway.

**Comment by Pro** [comment]
Crosslink:
https://forum.prosysopc.com/forum/opc-ua-java-sdk/cant-connect-to-open62541

**Comment by jpfr** [comment]
Oh, the OPC UA maestro @jouniaro is here.

So the java.lang.NullPointerException was thrown by user-code and not inside the SDK.
I take back that point. For Java non-experts it takes some time to interpret those trace logs.

The issue was fixed via 414032bcf917557444166cb907c8dd38e1d04602.

We had a regression on `master` when the initial HEL message is split into several packets.
(Even though chunking is not allowed for HEL, the network may split packets however it wants.)
So the connection was closed even though we should have waited for more packets.
Actually, with the Prosys Client, the HEL message comes in 33 packets that need to be reasembled.

Here's a Wireshark screenshot of this behavior
![prosys-hel](https://user-images.githubusercontent.com/1726411/28489353-836f5552-6ec2-11e7-8baf-d8a3d93309ae.png)

The Prosys client works great now!

**Comment by jouniaro** [comment]
Great to hear you managed to fix it and that it works both with IPV4 and IPV6.

The splitting of the packets is strange. AFAIK, the Java stack does not do anything special, but relies on standard Java libraries to perform the communication. So I have no idea why it splits that much in your environment.

(And yes, it's not always ((usually)) very easy to interpret the logs)
