### ISSUE TITLE
C11-specific feature used, while your description claims that it is C99 and C++98

### ISSUE THREAD

**Issue by yurivict** [open62541/open62541#1474]
clang-40 complains:
```
src/ua_types_encoding_binary.c:363:34: error: generic selections are a C11-specific feature [-Werror,-Wc11-extensions]
    else if(f == 0.0f) encoded = signbit(f) ? FLOAT_NEG_ZERO : 0;
                                 ^
/usr/include/math.h:134:20: note: expanded from macro 'signbit'
#define signbit(x) __fp_type_select(x, __signbitf, __signbit, __signbitl)
                   ^
/usr/include/math.h:82:39: note: expanded from macro '__fp_type_select'
#define __fp_type_select(x, f, d, ld) _Generic((x),                     \
                                      ^
```

 - [ ] open62541 Version (release number or git tag): 36ba8b3
 - [ ] Operating system: FreeBSD 11.1 amd64

**Comment by jpfr** [comment]
I think that is an artefact of your implementation of math.h, not our code.

signbit itself is defined for C99 math.h
http://en.cppreference.com/w/c/numeric/math/signbit

If you have a nice workaround, feel free to post a PR.
Otherwise, you can always remove the warning with the -Wno-c11-extensions flag.

Please reopen if this is unsolved.
