### ISSUE TITLE
units tests for both 32 and 64 bit

### ISSUE THREAD

**Issue by Stasik0** [open62541/open62541#152]
as seen in #149 we may have some issues on 32-bit systems that are unnoted by unit tests

therefore we need to get tests to comile and run on travis with -m32 flag, I gave up it in commits related to #148 since there are too many dependencies (non standard comiler gcc4.8, cmake from a package etc), so it is an open task

**Comment by ichrispa** [comment]
Hi @Stasik,

I have been using the master branch on 32bit (x86 and ARM) plattforms for quite some time now and I have not noticed any considerable problems that where not adressed here. Do you think this issue is still relevant?

If yes, what about an LXC system? It's simpler than docker and easy setup.

Best regards,

Chris

**Comment by Stasik0** [comment]
Hmm, can we use it in travis? I meant travis with the issue, otherwise the issue is old

**Comment by jpfr** [comment]
We cross-compile for 32bit on travis now.
