### ISSUE TITLE
Can the example server be considered stable or production ready?

### ISSUE THREAD

**Issue by w4tsn** [open62541/open62541#1650]
Question
===========
I did not find any related issue or passage in the documentation so here my question: 
Can the `example/server` implementation be considered stable or production ready? Since it is 'only' an example implementation. My impression though is more that this is a reference implementation than a mere example. Am I correct? I just want to double check.

**Comment by jpfr** [comment]
We do not develop servers. We develop a server SDK.

The `/example/server` server example is used to test against the Conformance Testing Tools of the OPC Foundation. The content of the server's information model is made specifically for that. And therefore not very interesting to the general public. Maybe have a look at the tutorials also in the example folder.

Production ready depends on your product.
If you want to deploy the SDK to a hardware solution that will live 30 years in the field, then I advise additional testing of the specific code version. Otherwise, let us convince you by the automated testing and the test coverage.

I can point to companies that use open62541 upon request via private message.

**Comment by w4tsn** [comment]
I see! Then I misunderstood the basic concept in the first place. I was thinking you'd provide a general reference server implementation which is configurable by config files, such that it is easily deployable within a config-management setting over multiple similar systems.
