### ISSUE TITLE
const correctness in Visual C++ 2017

### ISSUE THREAD

**Issue by nicolasr75** [open62541/open62541#2372]
## Description

Trying to compile the single-file distribution with Visual C++ 2017 I get errors because of char* parameters, like the following:

`Error	C2664	'UA_QualifiedName UA_QUALIFIEDNAME(UA_UInt16,char *)': cannot convert argument 2 from 'const char [11]' to 'char *'`	

Is there any reason why the char* parameters in these functions are not defined as 'const char*' ?
There are three other functions concerned, namely UA_STRING, UA_LOCALIZEDTEXT and UA_NODEID_STRING.
 Changing the signature to 'const char*' fixes the issue.

Related information:
https://stackoverflow.com/questions/48554625/vs-2017-doesnt-implicitly-convert-const-char-to-char

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.3.0 single-file distribution
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows 10 x64
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by hakanfriden** [comment]
Hi Nicolas!

Nice to read from someone using VS!
I have been struggling with the code in VS and found that following has to be set in order to compile a project in VS without errors or warnings. I suggest this is added to the open62541.pdf!

Open the project Properties, and set:
Configuration Properties
    C/C++
        Precompiled Headers
            Precompiled Header set to "Not Using Precompiled Headers"
        Advanced
            Compile As set to Compile as C Code (/TC)
    General
        Character Set - set to "Use Multi-Byte Character Set"
    Linker
        Input
            Additional Dependencies - add ws2_32.lib at start of line

I think your compiler Error would disappear withou you having to change the code. The thing is there are two types of char, one, or two bytes in size.

**Comment by nicolasr75** [comment]
Thanks Hakan for the quick response. 

So you say the signature of the methods has to be as it is to support either single or two-byte characters? That would mean the change from char* to const char* is impossible?

I am just asking for confirmation, because, as I see it, it would be a minor change in the code to fix it. As people in the StackOverflow post, that I quoted, mention, this is not just some Microsoft specific thing but the compiler is correctly complaining about code that is not valid according to the newest standard. 
Wouldn't it be nicer, to have standard-conformant code instead of using a compiler flag to suppress the error? Sorry, if I maybe misunderstand the problem.

What a great project by the way! Thanks to all for the hard work!!!

**Comment by Pro** [comment]
I also ran into that issue when usin open62541 ina C++ profect with a newer compiler. To fix the warning I added a const cast for all the string usages.

Maybe we can add these macros with a `_CONST` postfix, eg `UA_STRING_CONST()` and so on.

@jpfr?

**Comment by jpfr** [comment]
> Changing the signature to 'const char*' fixes the issue.

I vaguely recall of having done that on Linux.
And the compiler complained about the cast from `const char *` to `char *` inside the method.
Because we return a structure that points to the char-array as not const.

Good static code analysis tools (that we use) pick that up.

> Maybe we can add these macros with a _CONST postfix, eg UA_STRING_CONST() and so on.

That does not change that fact that we then return a string where the pointer is non-const.

**Comment by jpfr** [comment]
I don't see an immediate solution to this.
This will be something that C programmers will have to live with.

Please reopen to discuss concrete solution proposals.
