### ISSUE TITLE
 bi directional communication between opc ua client and server 

### ISSUE THREAD

**Issue by lakshmisivareddy** [open62541/open62541#2499]
Hi i am looking for sample bi directional communication between opc ua server and client

**Comment by Pro** [comment]
Did you google for a possible response to your question? Probably not, otherwise you would have found our documentation and examples:

https://open62541.org/doc/0.3/

https://github.com/open62541/open62541/tree/master/examples

When writing an issue, please try to stick to our issue template. For general questions like this use StackOverflow instead.
