### ISSUE TITLE
The cmake+Mingw32-make build OK, but do‘t found the file "open62541.h", the result like below picture

### ISSUE THREAD

**Issue by yanniupai** [open62541/open62541#2553]
![default](https://user-images.githubusercontent.com/29377917/53970229-346ad700-4135-11e9-8d77-482908f109a3.png)

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
did you look into src_generated?? Did you read our documentation, especially the chapter about UA_ENABLE_AMALGAMATION?

https://open62541.org/doc/current/building.html

Also, what exactly are you trying to achieve? What did you do to get to this point? How can we reproduce the steps? Please fill out the provided issue template, otherwise we are not able to help you.
