### ISSUE TITLE
How to create a certification and send this to server

### ISSUE THREAD

**Issue by AndyarcherReset** [open62541/open62541#2816]
Hi,
Now I want to create a UA client and then connect to a third part UA server with the Basic128Rsa15 and Basic256.
But seems that do not support this, right?

**Comment by SebsSa** [comment]
Right now, I'm working the other way around.
I want to generate a server and run it with Basic128Rsa15 and only allow a specific third party to use it. (UAExpert in my case)

That's why I'm not an expert, but maybe I can help you anyway. 


Read this through for yourself: 
https://github.com/open62541/open62541/issues/2637

and maybe use :
https://github.com/open62541/open62541/blob/master/tools/certs/create_self-signed.py  and
https://github.com/open62541/open62541/blob/master/examples/encryption/client_encryption.c

**Comment by jpfr** [comment]
This is definitely supported.

See here the example:
https://github.com/open62541/open62541/blob/master/examples/encryption/client_encryption.c

You can define which SecurityPolicy to use in the client config:
https://open62541.org/doc/current/client.html#client-configuration

**Comment by AndyarcherReset** [comment]
> This is definitely supported.
> 
> See here the example:
> https://github.com/open62541/open62541/blob/master/examples/encryption/client_encryption.c
> 
> You can define which SecurityPolicy to use in the client config:
> https://open62541.org/doc/current/client.html#client-configuration


Hi,
From the example client_encryption.c, I just see that can load the certificate.
But how can I create a certificate within the code? Or should I use another way to do this by myself?

**Comment by jpfr** [comment]
https://github.com/open62541/open62541/blob/master/tools/certs/create_self-signed.py
