### ISSUE TITLE
Compile Error of OPEN62541

### ISSUE THREAD

**Issue by xiaotian711** [open62541/open62541#2857]
![360截图20190630215652163](https://user-images.githubusercontent.com/52207459/60397690-1d3b7380-9b82-11e9-8853-675107f8d07a.jpg)
![360截图20190630215720883](https://user-images.githubusercontent.com/52207459/60397691-1d3b7380-9b82-11e9-9182-e7f6896c09e4.jpg)

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Stasik0** [comment]
It is not a compile error, is the server offering nosecurity endpoint?

**Comment by Pro** [comment]
You are probably trying to connect to a server, which does not provide an endpoint for username/password authentication. 

Since you did not fill out the issue template completely, there's essential information missing. I'll close this as unclear question.

Please extend your post with the necessary information, then we can have another look.
