### ISSUE TITLE
LDS ME  -> ServerOnNetworkCallback returns discovery url with hostname

### ISSUE THREAD

**Issue by magiino** [open62541/open62541#3581]
Hello,

This is not issue it's more like discussion if I understand and use the concepts well.

### 1
I'm running two opc ua servers on two different machines in local network (machines obtain IP address by DHCP). Both servers are LDS with other funcionality like DA, so application type is `_config->applicationDescription.applicationType = UA_APPLICATIONTYPE_SERVER;`

The problem is that `ServerOnNetworkCallback()` returns discovery url with hostname -> `opc.tcp://marek-ubuntu-ntbook:4850` and not with ip address `opc.tcp:192.168.0.221:4850` so the 
registering to LDS server fails, because client can't find server by discovery url with hostname.

What I have tried:
 - initialize discovery urls in server config `_config->applicationDescription.discoveryUrls`- this seems to not work.
 - I know about  `UA_ServerConfig_setCustomHostname()`

What is the correct approach to fix this problem?

### 2
Another issue is that the server is announcing itself every 5s even if I already register to him. So the next registration fails.
![image](https://user-images.githubusercontent.com/27290512/80768588-189d6e00-8b4b-11ea-8b75-ca15845fc124.png)
Should I store already registered LDS and filter out those announcements??

#### [UPDATE]
I found out its repeating just few times and then it stops.
![image](https://user-images.githubusercontent.com/27290512/80769923-03c2d980-8b4f-11ea-99fe-fbc6e9652941.png)

But after 5 minutes, the server receives next 36 announcements (as the first time).
Is this good behavior?

### 3
If I want register to more than one announced LDS server, can I use the same client instance for periodic registration?
`UA_StatusCode retVal = UA_Server_addPeriodicServerRegisterCallback(GetServer(), registerClient->GetClient(), endpointUrl, 10 * 60 * 1000, 500, NULL);`

### 4
```
UA_Client_findServersOnNetwork(UA_Client *client, const char *serverUrl,
                               UA_UInt32 startingRecordId, UA_UInt32 maxRecordsToReturn,
                               size_t serverCapabilityFilterSize, UA_String *serverCapabilityFilter,
                               size_t *serverOnNetworkSize, UA_ServerOnNetwork **serverOnNetwork) {
```
`UA_Client_findServersOnNetwork` do not find any servers if I use capability filter.
With discovery client from examples I can find both ua servers, with these capabilities.
![image](https://user-images.githubusercontent.com/27290512/80772021-8e0e3c00-8b55-11ea-87c1-0b2367c1cb3b.png)

But If I run method `UA_Client_findServersOnNetwork` with parameters as is shown below, it finds 0 servers ;
```
UA_String* serverCapabilityFilter = (UA_String*)UA_Array_new(3, &UA_TYPES[UA_TYPES_STRING]);
        serverCapabilityFilter[0] = UA_String_fromChars("LDS");
        serverCapabilityFilter[1] = UA_String_fromChars("DA");
        serverCapabilityFilter[2] = UA_String_fromChars("storage");

UA_Client_findServersOnNetwork("opc.tcp://localhost:4850", 0, 0, 3, serverCapabilityFilter , serverSize, servers);
```

FROM OPC UA DOCUMENTATION:
![image](https://user-images.githubusercontent.com/27290512/80772368-c8c4a400-8b56-11ea-936b-1089b61e3721.png)

Is it not working because I use custom capability like *transport* and *storage* ??

`My point is to filter out correct servers in search phase, without need of search in address space after connection.`

## Checklist
Please provide the following information:
 - [ x ] open62541 Version (release number or git tag): v1.0.1
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ Ubuntu 18.04.4 LTS ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
@Pro Can you have a look?

**Comment by Pro** [comment]
@magiino I will try to answer your questions:

1) LDS Hostname vs IP

The OPC UA Specification Part 12 defines, that the mDNS announcement can contain a hostname OR the ip address of the host (see https://reference.opcfoundation.org/v104/GDS/docs/C.3/). Independent of the discovery features, we use by default the hostname for the endpoint URL of the server.
The discovery code just takes the endpoint url and basically copies it to the mDNS announcement.
Therefore, the announced mDNS content is the same as the configured endpoint discovery URLs.
You can also use Wireshark with the `mdns` filter to see the messages.
In correctly set-up networks, a host should be able to resolve a hostname to the corresponding IP address. To manually hardcode it, you can add the hostname to `/etc/hosts`
In specific cases where the is no DNS server or the resolving doesn't work, it's possible to override the hostname with a specific IP address. This can be achieved by using `UA_ServerConfig_setCustomHostname()` and just passing an IP address.

An example is shown here for a microcontroller:
https://github.com/Pro/open62541-esp32/blob/d87a53e99fe3767027335f9dbaf9c37a44035ce6/main/main.c#L128

2) multiple mDNS announces

Our LDS-ME implementation just responds to any mDNS query for the opc ua namespace.
In your case it could be that another application sends a query every 5 minutes, and then there are multiple mDNS announces since there are multiple servers running in the same network announcing themselves to each other.
Use Wireshark with the `mdns` filter to see what's going on.

Typically you need to implement higher-level logic to filter out multiple announces. In addition, you also should implement some logic to detect, if it is an already known server, or if the server was restarted in between and therefore you need to re-browse. In my setups I'm caching the startup time and comparing it to see if it is a new instance.

3) Same client for multiple register calls

In general one client should also only be connected to one server, otherwise you always need to create new connections.
Since the periodic register handles the connection internally, I strongly recommend to use different clients for different servers. Just create a hash map from Endpoint-URL to Client.

4) Multiple capabilities filter

You are right: 
it looks like the corresponding filter code is wrong:
https://github.com/open62541/open62541/blob/f71912485ec60a42eebbfd96877bef5268c699e6/src/server/ua_services_discovery_multicast.c#L157

I need to create a fix for this.

**Comment by Pro** [comment]
@magiino can you please test #3588 if it fixes the capability filtering for you?

**Comment by magiino** [comment]
Thank you for amazing answer! I can confirm #3588 fix works.
