### ISSUE TITLE
What is difference between v1.2 and 1.1

### ISSUE THREAD

**Issue by EvgKlin** [open62541/open62541#4407]
## Description
What is difference between v1.2 and 1.1. Both versions are developed parallel and both versions are licensed under the Mozilla Public License. I don't understand a difference between these two releases 
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
v1.2 is newer and has more features. But it also changed the API in some (minor) ways to accomodate the new features.

We keep v1.1 release family alive to the extend possible.
So that people who don't want to handle the API change for 1.2 can still receive important bugfixes.

That's quite normal in software development.
Please close the issue if the questions is answered.
