### ISSUE TITLE
Set log level at runtime and/or change logger implementation at runtime via callbacks

### ISSUE THREAD

**Issue by JulZimmermann** [open62541/open62541#5280]
## Description

Hi,

my question is basically a duplicate of #2249 and #3334.

I use open62541 via the vcpkg library package manager, which compiles open62541 with the default log level option. I, therefore, have no way to specify the log level, which can only be set at compile time and not at runtime of the application. 

I'd really like the possibility to configure the log level output at runtime, and/or (even better) to change the logger (plugin) implementation at runtime, by providing callbacks. 

#2249 and #3334. suggest implementing your own logger functions, but as far as I can tell, these functions would currently need to exist at compile time of open62541. This is not possible in cases you want to use a pre-compiled version of the open62541 lib, installed via a package manager (vcpkg, Conan, apt, etc.)

Is there any way I overlooked, how I could redirect the logging output, or at least change the log level, without recompiling open62541?

If not: Would you consider a feature to allow this?

Thanks!

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag): 1.2.3
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by neojaw** [comment]
Your own logging plugin does not need to exist during compile time of open62541. When you create your server and/or client in your code, you just put the function pointer (and context pointer, if needed) into the config object and the server/client will call it. (You should even be able to swap the pointers out at runtime if you are careful but that seems like a bad idea to me.)

However, you are right in that, in order to work in the way you intend, you have to have open62541 compiled with a suitably verbose log level (ideally the highest) and then control through your own plugin what will actually get written. I think the default log level is 300 which will give you `INFO` and everything above. If you also need `DEBUG` and `TRACE`, you currently need a differently configured build, yes.
