### ISSUE TITLE
Could NOT find LATEX (missing: LATEX_COMPILER)

### ISSUE THREAD

**Issue by shaohuazhang1** [open62541/open62541#5325]
Description
When i execute configure on the cmake-gui ,error output as bellow:
bpf library not found. XDP functionalities will not be available.
Could NOT find LATEX (missing: LATEX_COMPILER) 
How to solve this problem?
Background Information / Reproduction Steps

Used CMake options:
![cmake option](https://user-images.githubusercontent.com/107022725/189266494-291e0fe2-0962-4811-8f11-43b5918bc241.PNG)

 Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):1.3.3
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:Ubuntu20.04
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by neojaw** [comment]
First off, the library compiles just fine without LaTeX, you just won't be able to build the documentation (which you arguably don't need to because you can find it online: [HTML](http://www.open62541.org/doc/1.3/toc.html), [PDF](https://open62541.org/doc/open62541-1.3.pdf)). So the line in the log is merely informational.

That being said, if you do want to build the documentation, you need to install LaTeX. On Ubuntu this should be some of the `texlive-something` packages. `texlive-latex-base` sounds like a good starting point. But be warned that the installation size is *huge*.

**Comment by shaohuazhang1** [comment]
get
thank you!
