### ISSUE TITLE
PubSub - unique flows

### ISSUE THREAD

**Issue by starcore2022** [open62541/open62541#5587]
## Description
I have been getting into OPC UA for a few months and I have been searching any way for the unique network flow described in DDS, to emulate it in OPC UA. Recently I found that there doesn't seems to be anything that could be linked to it. I was searching for the register that would tell me address of the subscriber and create a semi-unique connection between them, for QoS differentiation, but had no luck finding such.
I tried the MQTT PubSub examples as well as have been looking into the broker-less versions, but there doesn't seems to be anything that is similar.
I was wondering, whether someone could help me out with the knowledge of whether there is this function and I just missed it, or is it function that is planed for the future, or as of now has not been decided, whether to add it.
If there would at least be some of the needed parts in it, or setting the subscriber endpoint address or getting it out of the network, I would be grateful and I would try to write a solution myself.
Thank you for help in advance.

## Background Information
The purpose of unique network flows are to differentiate between communications of different nodes, by setting different QoS settings, with using semi-unique flows (making either the publisher, or subscriber unique). With the semi-unique flow the QoS can be set for each flow separately.

**Comment by jpfr** [comment]
Many years ago some core developers of open62541 created the link to DDS.
The most similar concept in the OPC UA world is PubSub communication with UDP-multicast.

It's been some time and I don't remember the specifics for unique network flow.
But maybe you mean *unicast sending* instead of multicast sending.
open62541 just a few weeks ago received the feature for unicast sending for PubSub over UDP.

Attached is the author version PDF of the conference publication here: https://ieeexplore.ieee.org/abstract/document/7496515
[manuscript.pdf](https://github.com/open62541/open62541/files/10480635/manuscript.pdf)

**Comment by starcore2022** [comment]
Thank you for the help, I didn't find this manuscript before and will be going through it.

**Comment by starcore2022** [comment]
Went through it and it seems that exactly how with DDS, but either with Unicast or getting the IP and port out of MQTT logging info should do what I need. Thanks for the help!
