### ISSUE TITLE
Remove `Slow Float Encoding.` warning?

### ISSUE THREAD

**Issue by Pro** [open62541/open62541#752]
What's the reason behind the `Slow Float Encoding` warning at https://github.com/open62541/open62541/blob/2fa33020b8e6fbe2a3acbd44b687177b599a9ba3/include/ua_config.h.in#L187

It is always shown when clang is used for build. Is this necessary?

E.g. see:
https://travis-ci.org/open62541/open62541/jobs/152919168

I think this slows down compilation time

**Comment by jpfr** [comment]
Clang does not define __FLOAT_WORD_ORDER__. So we cannot reliably detect whether floats can be  memcpy 'd on the network buffer.

Solutions:
- Use a custom program to detect this in cmake. (But not for the single-file release.)
- Make the warning appear in ua_types.c once instead of for every include of the config.

**Comment by jpfr** [comment]
fixed #759
